branch-defaults:
  default:
    environment: aster-STREAM
  master:
    environment: aster-STREAM
environment-defaults:
  aster-STREAM:
    branch: null
    repository: null
global:
  application_name: aster
  branch: null
  default_ec2_keyname: aster
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: thrive
  repository: null
  sc: null
  workspace_type: Application
tbranch-defaults:
  default:
    environment: aster-STREAM
